name: publish artifacts

on:
  push:
    branches:
      - '**/191_artifact_server_setup'
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.gitignore'
  release:
    types: [released]
  workflow_dispatch:


jobs:
  run-indexing:
    runs-on: ubuntu-latest

    steps:
      - name: Print release info
        run: |
          echo "Release triggered: ${{ github.event.release.tag_name }}"
          echo "Release URL: ${{ github.event.release.html_url }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG="${{ github.event.release.tag_name }}"
          mkdir -p $TAG
          gh release download "$TAG" --dir ./downloaded-assets
          ls -la ./downloaded-assets/
            # - name: Save Release Folder as Artifact
